spring:
  application:
    name: iot
  config:
    import:
      - optional:file:.env[.properties]

server:
  port: 8080

mqtt:
  broker-url: ${MQTT_BROKER_URL}
  client-id: ${MQTT_CLIENT_ID:iot-server}
